<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RetailStorePOS.Data\RetailStorePOS.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\logo.png" />
    <Resource Include="Resources\Policies\retail_store_pos_terms_and_privacy_policy.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\UI\hero-ui-frontend\dist\**\*">
      <Link>HeroUi\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MahApps.Metro.IconPacks.Material" Version="6.2.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3800.47" />
    <PackageReference Include="QuestPDF" Version="2025.1.2" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    
    <!-- Extreme Boot & RAM Optimizations removed in favor of lower max RAM -->
    <!-- PublishReadyToRun, PublishSingleFile, TieredPGO removed -->

    <TieredCompilationQuickJit>true</TieredCompilationQuickJit>
    <TieredCompilation>true</TieredCompilation>

    <OutputType>WinExe</OutputType>
    <IsTestProject>false</IsTestProject>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>$(RetailStorePOSExecutableName)</AssemblyName>
    <TargetName>$(RetailStorePOSExecutableName)</TargetName>
    <Product>$(RetailStorePOSProductName)</Product>
    <Title>$(RetailStorePOSDescription)</Title>
    <Company>$(RetailStorePOSBrandName)</Company>
    <Description>$(RetailStorePOSDescription)</Description>
    <Authors>$(RetailStorePOSBrandName)</Authors>
    <ApplicationIcon>$(RetailStorePOSAppIcon)</ApplicationIcon>
    <Version>$(RetailStorePOSVersion)</Version>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

</Project>
